cloud:
  aws:
    credentials:
      access-key: AKIAZS7UYRA7KEPZO6EF
      secret-key: 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
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: apicloudstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090